apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-api
  namespace: {{ .Values.namespace }}
  labels:
    app: recommendation-api
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: recommendation-api
  template:
    metadata:
      labels:
        app: recommendation-api
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          envFrom:
            - configMapRef:
                name: recommendation-config
            {{- if .Values.externalSecret.enabled }}
            - secretRef:
                name: {{ .Values.externalSecret.secretName }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.readinessProbe.path }}
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.livenessProbe.path }}
              port: {{ .Values.deployment.port }}
            initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
