{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recommendation-config-dynamic
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.clusterSecretStore }}
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/msk/bootstrap_brokers
    - secretKey: ELASTICSEARCH_URL
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/opensearch/endpoint
    - secretKey: PGVECTOR_ENDPOINT
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/pgvector/endpoint
    - secretKey: PGVECTOR_SECRET_ARN
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/pgvector/secret_arn
{{- end }}
