apiVersion: v1
kind: Service
metadata:
  name: recommendation-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  selector:
    app: recommendation-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
