apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.5
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: glue
            - name: DEFAULT_REGION
              value: us-east-1
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: infra
spec:
  selector:
    app: localstack
  ports:
    - port: 4566
      targetPort: 4566
