{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: analytics-env-dynamic
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.clusterSecretStore }}
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/msk/bootstrap_brokers
    - secretKey: ELASTICSEARCH_URL
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/opensearch/endpoint
    - secretKey: ICEBERG_WAREHOUSE
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/iceberg/warehouse
    - secretKey: GLUE_SCHEMA_REGISTRY_NAME
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/glue/schema_registry
    - secretKey: ATHENA_WORKGROUP
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/athena/workgroup
    - secretKey: ATHENA_RESULTS_BUCKET
      remoteRef:
        key: {{ .Values.externalSecret.ssmPathPrefix }}/athena/results_bucket
{{- end }}
