# Allow all app namespaces to access Kafka in infra namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kafka-access
  namespace: infra
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: videostreamingplatform
      ports:
        - port: 9092
          protocol: TCP
---
# Allow recommendations namespace to access pgvector in infra namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pgvector-access
  namespace: infra
spec:
  podSelector:
    matchLabels:
      app: pgvector
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: videostreamingplatform
      ports:
        - port: 5432
          protocol: TCP
---
# Allow analytics + recommendations namespaces to access Elasticsearch in videostreamingplatform namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-elasticsearch-access
  namespace: videostreamingplatform
spec:
  podSelector:
    matchLabels:
      app: elasticsearch
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: videostreamingplatform
      ports:
        - port: 9200
          protocol: TCP
---
# Allow all app namespaces to access LocalStack (Glue Schema Registry) in infra namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-localstack-access
  namespace: infra
spec:
  podSelector:
    matchLabels:
      app: localstack
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: videostreamingplatform
      ports:
        - port: 4566
          protocol: TCP
