apiVersion: v1
kind: ServiceAccount
metadata:
  name: videostreamingplatform-sa
  namespace: videostreamingplatform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-sa
  namespace: infra
