apiVersion: v1
kind: ServiceAccount
metadata:
  name: videostreamingplatform-sa
  namespace: videostreamingplatform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-sa
  namespace: analytics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendations-sa
  namespace: recommendations
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-sa
  namespace: infra
