apiVersion: v1
kind: ServiceAccount
metadata:
  name: videostreamingplatform-sa
  namespace: videostreamingplatform
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-sa
  namespace: infra
imagePullSecrets:
  - name: ghcr-pull
