apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analytics
  namespace: argocd
spec:
  project: data
  source:
    repoURL: https://github.com/rajesh-proddu/videostreamingplatform-analytics.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: analytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
