apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/rajesh-proddu/videostreamingplatform-infra.git
    targetRevision: master
    path: elasticsearch
  destination:
    server: https://kubernetes.default.svc
    namespace: videostreamingplatform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
