apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://github.com/rajesh-proddu/videostreamingplatform-infra.git
      targetRevision: master
      path: kafka
    - repoURL: https://github.com/rajesh-proddu/videostreamingplatform-infra.git
      targetRevision: master
      path: schema-registry
    - repoURL: https://github.com/rajesh-proddu/videostreamingplatform-infra.git
      targetRevision: master
      path: pgvector
    - repoURL: https://github.com/rajesh-proddu/videostreamingplatform-infra.git
      targetRevision: master
      path: networking
    - repoURL: https://github.com/rajesh-proddu/videostreamingplatform-infra.git
      targetRevision: master
      path: rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
