apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendations
  namespace: argocd
spec:
  project: data
  source:
    repoURL: https://github.com/yourusername/videostreamingplatform-recommendations.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: recommendations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
