apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform services (main app + infra + elasticsearch + analytics + recommendations)
  sourceRepos:
    - https://github.com/rajesh-proddu/videostreamingplatform.git
    - https://github.com/rajesh-proddu/videostreamingplatform-infra.git
  destinations:
    - namespace: videostreamingplatform
      server: https://kubernetes.default.svc
    - namespace: infra
      server: https://kubernetes.default.svc
    - namespace: analytics
      server: https://kubernetes.default.svc
    - namespace: recommendations
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
